version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mariaDb:/var/lib/mysql
    env_file:
      - ".env.local"
    environment:
      - TZ=Europe/Prague
volumes:
  mariaDb: