import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ColorComponent } from "../components/colors.component";
import { Time } from "../components/time.component";
import { WeatherComponent } from "../components/weather.component";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Office Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Time />
          </div>
          <div className={styles.card}>
            <WeatherComponent />
          </div>
          <div className={styles.card}>
            <ColorComponent />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
